name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      TAGS:
        description: 'Number Of Retries'
        required: true
        default: "@search" # Default value is now an array
        type: string
      THREAD_COUNT:
        description: 'Number Of Threads'
        required: true
        default: "3" # Default value is now an array
        type: string
permissions:
    contents: read
    pages: write
    id-token: write
jobs:
  test:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test -g "${{github.event.inputs.TAGS}}" --workers=${{github.event.inputs.THREAD_COUNT}}
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
    - name: Upload Pages Artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: playwright-report
        retention-days: 3   
    - name: Setup Pages
      uses: actions/configure-pages@v2
    - uses: actions/download-artifact@v2
      with:
          name: 'github-pages' 
    - name: Deploy to GitHub Pages
      id: github-pages
      uses: actions/deploy-pages@v1
        
